<html>
<head>
<title>::Leave Request Confirmation::</title>
<?php
session_start();
include 'connect.php';
include 'mailer.php';
include 'adminnavi.php';

require_once 'dompdf/autoload.inc.php'; 
 
// Reference the Dompdf namespace 
use Dompdf\Dompdf; 

$user = $_SESSION['adminuser'];
echo "<link rel='stylesheet' type='text/css' href='style.css'>";
echo "<div class = 'textview'>";
echo "<center>";
if(isset($user))
	{
	$leavetype = $_POST['leavetype'];
	$leavedays = $_POST['leavedays'];
	$leavedate = $_POST['leaveyear']."-".$_POST['leavemonth']."-".$_POST['leavedate'];
	$endleavedate = $_POST['endleaveyear']."-".$_POST['endleavemonth']."-".$_POST['endleavedate'];
	$date = date_create($leavedate);
	$duration = $leavedays." days";
	$interval = date_interval_create_from_date_string($duration);
	$enddate = date_add($date,$interval);
	$end = date_format($enddate,"Y-m-d");
	$empname = $_POST['empname'];
	$emptype = $_POST['emptype'];
	$designation = $_POST['designation'];
	$emptype = $_POST['emptype'];
	$empfee = $_POST['empfee'];


	$rownumber = $_POST['rownumber'];
	$n = 0;
	for($i = 0; $i < $rownumber; $i++){
		$value1 = $_POST['value'.++$n];
		$value2 = $_POST['value'.++$n];
		$value3 = $_POST['value'.++$n];
		$value4 = $_POST['value'.++$n];
		$value5 = $_POST['value'.++$n];
		$value6 = $_POST['value'.++$n];
		$value7 = $_POST['value'.++$n];
		$query = "INSERT INTO engagementrecord VALUES('".$value1."','".$value2."','".$value3."','".$value4."','".$value5."','".$value6."','".$value7."')";
		mysqli_query($conn, $query);

	}
	
	$leavereason = $_POST['leavereason'];
	$dept = $_POST['dept'];

	$target_dir = "applications/";
	$target_file = $target_dir.basename($_FILES['application']['name']);

	if (move_uploaded_file($_FILES['application']['tmp_name'], $target_file))
		{
		$target_location="applications/".basename($_FILES['application']["name"]);
		$ext = pathinfo($target_location, PATHINFO_EXTENSION);
		$new="applications/".$_SESSION['adminuser'].$leavedate.".".$ext;
		rename($target_location,$new);
		// header('location:home.php');
		}


		if(!empty($leavedays)){
			if(strtotime($leavedate) > time()){
				$sql = "SELECT * FROM admins WHERE username='".$user."'";
				$result = $conn->query($sql);

				if ($result->num_rows > 0) {
					while($row = $result->fetch_assoc()) {
						if($row["username"] == $user){

							$empname = $row["EmpName"];
							$to = $row["email"];
							$name = "leaves/".$user.$leavedate.$leavetype.$end.'.pdf';
							echo "Inserted command ran";
							$sql2 = "INSERT INTO hod_leaves(EmpName,LeaveType,LeaveDays,StartDate,EndDate,Dept) VALUES('".$empname."','".$leavetype."','".$leavedays."','".$leavedate."','".$end."','".$row['Dept']."')";
							if (mysqli_query($conn, $sql2)){
								/* Teacher MAIL SECTION*/
								$msg = "The Leave Request generated by you is as follows : <br>Employee Name : ".$empname."<br>Leave Days Requested : ".$leavedays."<br>Type of leave : ".$leavetype."<br>Starting Date of Leave : ".$leavedate."<br><br><br>Thank You,<br>webadmin,Leave Management System.";
								$subject = "Leave Request Sent";
								$statusteacher = mailer($to,$msg,$subject);
								/* HOD MAIL SECTION*/

								$sql2 = "SELECT * FROM principal";
								if($conn->query($sql2) == TRUE){
									$result = $conn->query($sql2);
									if($result->num_rows > 0){
										while($row2 = $result->fetch_assoc()){
													$hodmailid = $row2['email'];
										}
									}
								}
								$msg = "The Leave Request is as follows : <br>Employee Name : ".$empname."<br>Leave Days Requested : ".$leavedays."<br>Type of leave : ".$leavetype."<br>Starting Date of Leave : ".$leavedate."<br><br><br>Thank You,<br>webadmin,Leave Management System.";
								$subject = "Leave Request from ".$empname;
								$statushod = mailer($hodmailid,$msg,$subject);
									
								if($statusteacher == true)
									$teachermsg =  "Request Has Been Sucessfully To HOD.<br/>Please Check Your email for your leave request<br/>";
								if($statushod == true)
									$hodmsg =  "Request Has Been Sucessfully Submitted.<br/>Please Check Your email for your leave request<br/>";
							}
							else
							{
							echo "Error: " . $sql . "<br>" . mysqli_error($conn);
							}
									
						}
					}
				}
				error_reporting(0);

				// $target_dir = "applications/";
				// $FileName = $_FILES["application"]["name"];
				// $TmpName = $_FILES["application"]["tmp_name"];
				// move_uploaded_file($TmpName,$FileName);


				
				
				// Instantiate and use the dompdf class 
				$dompdf = new Dompdf();
				
				$strm = '';
				$n = 0;
				for ($i = 0; $i <$rownumber;$i++){

					$strm .='
					<tr>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					<td>'.$_POST['value'.++$n].'</td>
					</tr>';
				}
				$engineering = array("Computer Science and Engineering ","Electronics and Telecommunication Engineering", "Civil Engineering", "Mechanical Engineering","Electronics and Electrical Engineering");
				$eng = array("CSE","ET&T","CIVIL","MECH","EEE");
				$department = "";
				for ( $t = 0; $t<4; $t++){
					if($eng[$t] == $dept){
						$department = $engineering[$t]; 
					}
				}
				$pdf_content='
							<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
							<html xmlns="http://www.w3.org/1999/xhtml">
							<head>
							<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
							</head>
						
							<style type="text/css">							
								#pdf_header, #pdf_container{ padding:10px; align : center;}				
								#pdf_header{ margin:10px auto 0px; border-bottom:none; font-family: sans-serif; line-height:1.6; }				
								table{width:100%;  border: 1px solid black; }				
								#pdf_container{margin:0px auto; }
								.rpt_title{ background:#99CCFF; }
								tr{font-family: sans-serif;text-align: right;}
								td{text-align:left;}
								th{text-align: left; }
								#engagement td,#engagement th{border-collapse: collapse; border:1px solid black; }															
							</style>
											
							<body>
							<div id="pdf_header" >
							To ,<br>
							The Prrincipal,<br>
							'.$department.',<br>
							Government Engineering College, Raipur(C.G)<br><br>

							Subject : Application for Leave and Engaging classes.<br><br>

							Respected Sir,<br><br>

							With due Respect I want to inform you that I Mr/Mrs '.$empname.' would like to take leave of '.$leavedays.'
							days from '.$leavedate.' to '.$endleavedate.' because '.$leavereason.'.<br>

							Kindly grant me leave of absense. <br><br>				
									
								

								<span>Thank You.</span><br><br><br>


								<div style = "float:right;">
								Your sincearly <br>
								Name of the Faculty : Mr/Mrs '.$empname.'<br>
								Department '.$dept.'<br>
								</div>
							</div></body></html>'
							;
							// $name = $user.$leavedate.$leavetype.$end.'.pdf';
							// $reportPDF = createPDF($pdf_content, $name);

							$dompdf->loadHtml($pdf_content); 
							
							// (Optional) Setup the paper size and orientation 
							$dompdf->setPaper('A4', 'portrait'); 
							
							// Render the HTML as PDF 
							$dompdf->render(); 
							
							// Output the generated PDF (1 = download and 0 = preview) 
							// $dompdf->stream("codexworld", array("Attachment" => 0));
							$name = "leaves/".$user.$leavedate.$leavetype.$end.'.pdf';
							file_put_contents($name,$dompdf->output());
							$conn->close();
							echo $hodmsg."\n".$teachermsg;
							echo "<script>
								window.location.href='my_leaves.php';
								</script>";
			}
			else
				{
				header('location:request_leave.php?err='.urlencode('Start Date is invalid !'));
				}
		}
		else
			{
			header('location:request_leave.php?err='.urlencode('Pl. Enter some details !'));
			}
}
else
{
header('location:index.php?err='.urlencode('Please Login first to access this page'));
}
echo "</center>";
echo "</div>";
function createPDF($pdf_content, $filename){
	
	$path='leaves/';
	$dompdf=new DOMPDF();
	$dompdf->load_html($pdf_content);
	$dompdf->render();
	$output = $dompdf->output();
	file_put_contents($path.$filename, $output);
	return $filename;		
	}
?>

<script type="text/javascript">
        function noBack()
         {
             window.history.forward()
         }
        noBack();
        window.onload = noBack;
        window.onpageshow = function(evt) { if (evt.persisted) noBack() }
        window.onunload = function() { void (0) }
    </script>
</head>
</html>